services: 
  portfolio:
    build: .
    container_name: react-portfolio
    
    ports:
      - "5173:5173"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - CHOKIDAR_UPSCALLING=true
